version: '3'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./test/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./test/nextcloud:/var/www/html
    restart: always

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./test/data/nginx:/etc/nginx/conf.d
      - ./test/data/certbot/conf:/etc/letsencrypt
      - ./test/data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./test/data/certbot/conf:/etc/letsencrypt
      - ./test/data/certbot/www:/var/www/certbot
